using MemoryPack;

namespace CryptoUtility;

/// <summary>
/// Defines a version-tolerant envelope format for storing data encrypted with a symmetric cipher.
/// Encapsulates all required parameters for decryption.
/// </summary>
[MemoryPackable(GenerateType.VersionTolerant)]
public partial class SymmetricCipherEnvelope
{
    [MemoryPackIgnore]
    public const int LatestVersion = 1;

    /// <summary>
    /// Protocol version used to interpret this encrypted payload.
    /// </summary>
    [MemoryPackOrder(0)]
    public readonly int Version;

    /// <summary>
    /// Identifier for the symmetric cipher algorithm used for encryption.
    /// </summary>
    [MemoryPackOrder(1)]
    public readonly SymmetricCipherID CipherID;

    /// <summary>
    /// Unique nonce required for the encryption operation.
    /// Must be the same value used during encryption for successful decryption.
    /// </summary>
    /// <remarks>
    /// It may be an empty byte array if no nonce is used, but it will never be null.
    /// </remarks>
    [MemoryPackOrder(2)]
    public readonly byte[] Nonce;

    /// <summary>
    /// Authentication tag generated by the AEAD cipher.
    /// Used to verify integrity and authenticity of both ciphertext and AAD.
    /// </summary>
    /// <remarks>
    /// This field is only used in AE and AEAD ciphers, for other ciphers it will return an empty byte array, but it
    /// will never be null.
    /// </remarks>
    [MemoryPackOrder(3)]
    public readonly byte[] Tag;

    /// <summary>
    /// Additional Authenticated Data (AAD).
    /// Represents data that is not encrypted but is included in the authentication tag
    /// of an AEAD cipher. This ensures integrity and tamper detection without affecting
    /// the ciphertext, making it suitable for metadata such as protocol headers.
    /// </summary>
    /// <remarks>
    /// This field is only used in AEAD ciphers, for other ciphers it will return an empty byte array, but it will never
    /// be null.
    /// </remarks>
    [MemoryPackOrder(4)]
    public readonly byte[] Aad;

    /// <summary>
    /// The encrypted data produced by the cipher.
    /// </summary>
    /// <remarks>
    /// This field is used in all symmetric ciphers.
    /// It may be an empty byte array if the payload is invalid, but it will never be null.
    /// </remarks>
    [MemoryPackOrder(5)]
    public readonly byte[] Ciphertext;

    [MemoryPackConstructor]
    public SymmetricCipherEnvelope(
        int version,
        SymmetricCipherID cipherID,
        byte[] nonce,
        byte[] tag,
        byte[] aad,
        byte[] ciphertext
    )
    {
        Version = version;
        Nonce = nonce;
        Tag = tag;
        Aad = aad;
        Ciphertext = ciphertext;
        ThrowIfAnyNull(nonce, tag, aad, ciphertext);
    }

    public byte[] ToBytes()
    {
        byte[] bytes = ToBytes(this);
        return bytes;
    }

    public string ToBase64()
    {
        string base64 = ToBase64(this);
        return base64;
    }

    public static string ToBase64(SymmetricCipherEnvelope envelope)
    {
        byte[] envelopeBytes = ToBytes(envelope);
        string envelopeBase64 = Convert.ToBase64String(envelopeBytes);
        return envelopeBase64;
    }

    public static SymmetricCipherEnvelope? FromBase64(string envelopeBase64)
    {
        byte[] envelopeBytes = Convert.FromBase64String(envelopeBase64);
        SymmetricCipherEnvelope? envelope = FromBytes(envelopeBytes);
        return envelope;
    }

    public static byte[] ToBytes(SymmetricCipherEnvelope envelope)
    {
        byte[] result = MemoryPackSerializer.Serialize(envelope);
        return result;
    }

    public static SymmetricCipherEnvelope? FromBytes(byte[] cryptoEnvelopeBytes)
    {
        SymmetricCipherEnvelope? result = MemoryPackSerializer.Deserialize<SymmetricCipherEnvelope>(
            cryptoEnvelopeBytes
        );

        return result;
    }

    private void ThrowIfAnyNull(params object?[] objects)
    {
        foreach (object? obj in objects)
        {
            if (obj == null)
            {
                throw new InvalidOperationException("Required parameter is null.");
            }
        }
    }
}
