name: Builder

on:
  workflow_dispatch:

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test CryptoUtility.Tests/CryptoUtility.Tests.csproj --no-restore

      - name: Build CryptoUtility
        run: dotnet build CryptoUtility/CryptoUtility.csproj -c Release --no-restore

      - name: Build CryptoUtility.Extras
        run: dotnet build CryptoUtility.Extras/CryptoUtility.Extras.csproj -c Release --no-restore

      - name: Build CryptoUtility.HkdfStandard
        run: dotnet build CryptoUtility.HkdfStandard/CryptoUtility.HkdfStandard.csproj -c Release --no-restore

      - name: Build CryptoUtility.Sample
        run: dotnet build CryptoUtility.Sample/CryptoUtility.Sample.csproj -c Release --no-restore
